name = "Parsers"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
authors = ["quinnj <quinn.jacobd@gmail.com>"]
version = "2.5.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[compat]
SnoopPrecompile = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Serialization", "Test"]
